export 'package:dosificacion/app/modules/absorcion/absorcion_binding.dart';
export 'package:dosificacion/app/modules/crono/crono_binding.dart';
export 'package:dosificacion/app/modules/cuagulacion/cuagulacion_binding.dart';
export 'package:dosificacion/app/modules/desinfeccion/desinfeccion_binding.dart';
export 'package:dosificacion/app/modules/dosificacion/dosificacion_binding.dart';
export 'package:dosificacion/app/modules/estabilizacion/estabilizacion_binding.dart';
export 'package:dosificacion/app/modules/floculacion/floculacior_binding.dart';
export 'package:dosificacion/app/modules/home/home_binding.dart';
export 'package:dosificacion/app/modules/oxidacion/oxidacion_binding.dart';
