export 'package:dosificacion/app/modules/absorcion/absorcion_screen.dart';
export 'package:dosificacion/app/modules/crono/crono_screen.dart';
export 'package:dosificacion/app/modules/cuagulacion/cuagulacion_screen.dart';
export 'package:dosificacion/app/modules/desinfeccion/desinfeccion_screen.dart';
export 'package:dosificacion/app/modules/dosificacion/dosificacion_screen.dart';
export 'package:dosificacion/app/modules/estabilizacion/estabilizacion_screen.dart';
export 'package:dosificacion/app/modules/floculacion/floculacion_screen.dart';
export 'package:dosificacion/app/modules/home/home_screen.dart';
export 'package:dosificacion/app/modules/oxidacion/oxidacion_screen.dart';
